<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>The Nasvad Website</title>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<style>';
echo 'body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}';
echo '.w3-row-padding img {margin-bottom: 12px}';
echo '/* Set the width of the sidebar to 120px */';
echo '.w3-sidebar {width: 120px;background: #222;}';
echo '/* Add a left margin to the "page content" that matches the width of the sidebar (120px) */';
echo '#main {margin-left: 120px}';
echo '/* Remove margins from "page content" on small screens */';
echo '@media only screen and (max-width: 600px) {#main {margin-left: 0}}';
echo '</style>';
echo '</head>';
echo '<body class="w3-black">';
echo '';
echo '<!-- Icon Bar (Sidebar - hidden on small screens) -->';
echo '<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">';
echo '<!-- Avatar image in top left corner -->';
echo '<img src="/w3images/avatar_smoke.jpg" style="width:100%">';
echo '<a href="#" class="w3-bar-item w3-button w3-padding-large w3-black">';
echo '<i class="fa fa-home w3-xxlarge"></i>';
echo '<p>HOME</p>';
echo '</a>';
echo '<a href="#about" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-user w3-xxlarge"></i>';
echo '<p>ABOUT</p>';
echo '</a>';
echo '<a href="#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-eye w3-xxlarge"></i>';
echo '<p>PHOTOS</p>';
echo '</a>';
echo '<a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-envelope w3-xxlarge"></i>';
echo '<p>CONTACT</p>';
echo '</a>';
echo '</nav>';
echo '';
echo '<!-- Navbar on small screens (Hidden on medium and large screens) -->';
echo '<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">';
echo '<div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">';
echo '<a href="#" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>';
echo '<a href="#about" class="w3-bar-item w3-button" style="width:25% !important">ABOUT</a>';
echo '<a href="#photos" class="w3-bar-item w3-button" style="width:25% !important">SERVICES</a>';
echo '<a href="#contact" class="w3-bar-item w3-button" style="width:25% !important">CONTACT</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Page Content -->';
echo '<div class="w3-padding-large" id="main">';
echo '<!-- Header/Home -->';
echo '<header class="w3-container w3-padding-32 w3-center w3-black" id="home">';
echo '<h1 class="w3-jumbo"><span class="w3-hide-small">I'm</span> Nasvad</h1>';
echo '<p>Programmer and Web Designer</p>';
echo '<img src="avatar/eu.jpg" alt="boy" class="w3-image" width="992" height="1108">';
echo '</header>';
echo '';
echo '<!-- About Section -->';
echo '<div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">';
echo '<h2 class="w3-text-light-grey">My Name</h2>';
echo '<hr style="width:200px" class="w3-opacity">';
echo '<p>Some text about me. Some text about me. I am lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip';
echo 'ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur';
echo 'adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.';
echo '</p>';
echo '<h3 class="w3-padding-16 w3-text-light-grey">My Skills</h3>';
echo '<p class="w3-wide">Programming</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:95%"></div>';
echo '</div>';
echo '<p class="w3-wide">Web Design</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:85%"></div>';
echo '</div>';
echo '<p class="w3-wide">Database</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:80%"></div>';
echo '</div><br>';
echo '';
echo '<div class="w3-row w3-center w3-padding-16 w3-section w3-light-grey">';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">11+</span><br>';
echo 'Partners';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">55+</span><br>';
echo 'Projects Done';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">89+</span><br>';
echo 'Happy Clients';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">150+</span><br>';
echo 'Meetings';
echo '</div>';
echo '</div>';
echo '';
echo '<button class="w3-button w3-light-grey w3-padding-large w3-section">';
echo '<i class="fa fa-download"></i> Download Resume';
echo '</button>';
echo '';
echo '<!-- Grid for pricing tables -->';
echo '<h3 class="w3-padding-16 w3-text-light-grey">My Price</h3>';
echo '<div class="w3-row-padding" style="margin:0 -16px">';
echo '<div class="w3-half w3-margin-bottom">';
echo '<ul class="w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off">';
echo '<li class="w3-dark-grey w3-xlarge w3-padding-32">Basic</li>';
echo '<li class="w3-padding-16">Web Design</li>';
echo '<li class="w3-padding-16">2 Websites</li>';
echo '<li class="w3-padding-16">5GB Storage</li>';
echo '<li class="w3-padding-16">Mail Support</li>';
echo '<li class="w3-padding-16">';
echo '<h2>$ 25</h2>';
echo '<span class="w3-opacity">per month</span>';
echo '</li>';
echo '<li class="w3-light-grey w3-padding-24">';
echo '<button class="w3-button w3-white w3-padding-large w3-hover-black">Sign Up</button>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="w3-half">';
echo '<ul class="w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off">';
echo '<li class="w3-dark-grey w3-xlarge w3-padding-32">Pro</li>';
echo '<li class="w3-padding-16">Web Design</li>';
echo '<li class="w3-padding-16">5 Websites</li>';
echo '<li class="w3-padding-16">50GB Storage</li>';
echo '<li class="w3-padding-16">Endless Support</li>';
echo '<li class="w3-padding-16">';
echo '<h2>$ 50</h2>';
echo '<span class="w3-opacity">per month</span>';
echo '</li>';
echo '<li class="w3-light-grey w3-padding-24">';
echo '<button class="w3-button w3-white w3-padding-large w3-hover-black">Sign Up</button>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<!-- End Grid/Pricing tables -->';
echo '</div>';
echo '';
echo '<!-- Testimonials -->';
echo '<h3 class="w3-padding-24 w3-text-light-grey">My Reputation</h3>';
echo '<img src="avatar/bruno.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Bruno Diferente.</span> CEO at Mighty Schools.</p>';
echo '<p>Nasvad saved me from a web disaster.</p><br>';
echo '';
echo '<img src="avatar/weskley.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Weskley do Rock.</span> CEO at Company.</p>';
echo '<p>No one is better than Nasvad.</p>';
echo '<!-- End About Section -->';
echo '</div>';
echo '';
echo '<!-- Portfolio Section -->';
echo '<div class="w3-padding-64 w3-content" id="photos">';
echo '<h2 class="w3-text-light-grey">My Photos</h2>';
echo '<hr style="width:200px" class="w3-opacity">';
echo '';
echo '<!-- Grid for photos -->';
echo '<div class="w3-row-padding" style="margin:0 -16px">';
echo '<div class="w3-half">';
echo '<img src="img/sol.jpg" style="width:100%">';
echo '<img src="img/por do sol.jpg" style="width:100%">';
echo '<img src="img/ceu.jpg" style="width:100%">';
echo '</div>';
echo '';
echo '<div class="w3-half">';
echo '<img src="img/ceu.jpg" style="width:100%">';
echo '<img src="img/por do sol.jpg" style="width:100%">';
echo '<img src="img/sol.jpg" style="width:100%">';
echo '<img src="img/chorro.jpg" style="width:100%">';
echo '</div>';
echo '<!-- End photo grid -->';
echo '</div>';
echo '<!-- End Portfolio Section -->';
echo '</div>';
echo '';
echo '<!-- Contact Section -->';
echo '<div class="w3-padding-64 w3-content w3-text-grey" id="contact">';
echo '<h2 class="w3-text-light-grey">Contact Me</h2>';
echo '<hr style="width:200px" class="w3-opacity">';
echo '';
echo '<div class="w3-section">';
echo '<p><i class="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Crato, CE</p>';
echo '<p><i class="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Phone: +00 151515</p>';
echo '<p><i class="fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i> Email: ynasvad@gmail.com</p>';
echo '</div><br>';
echo '<p>Let's get in touch. Send me a message:</p>';
echo '';
echo '<form action="/action_page.php" target="_blank">';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Name" required name="Name"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Email" required name="Email"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Subject" required name="Subject"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Message" required name="Message"></p>';
echo '<p>';
echo '<button class="w3-button w3-light-grey w3-padding-large" type="submit">';
echo '<i class="fa fa-paper-plane"></i> SEND MESSAGE';
echo '</button>';
echo '</p>';
echo '</form>';
echo '<!-- End Contact Section -->';
echo '</div>';
echo '';
echo '<!-- Footer -->';
echo '<footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">';
echo '<i class="fa fa-facebook-official w3-hover-opacity"></i>';
echo '<i class="fa fa-instagram w3-hover-opacity"></i>';
echo '<i class="fa fa-snapchat w3-hover-opacity"></i>';
echo '<i class="fa fa-pinterest-p w3-hover-opacity"></i>';
echo '<i class="fa fa-twitter w3-hover-opacity"></i>';
echo '<i class="fa fa-linkedin w3-hover-opacity"></i>';
echo '<p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>';
echo '<!-- End footer -->';
echo '</footer>';
echo '';
echo '<!-- END PAGE CONTENT -->';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>